# Generated by Django 4.1.3 on 2022-12-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="articulo",
        ),
        migrations.DeleteModel(
            name="cliente",
        ),
    ]
